{% set version = "5.0b03" %}

# NOTE: this could go back to 1.8 when bumping to >=v5.0b02, because compat was restored in
#       https://github.com/InsightSoftwareConsortium/ITK/commit/c090e650ab0e2062
{% set hdf5_version = ">=1.10.4" %}

package:
  name: libitk
  version: "{{version}}"

source:
  #url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  #sha256: 7bf11a8be1352f7f9d68e8f759f8ebf60d922c8eb4436be7de26fb6c2ecac065
  git_url: https://github.com/InsightSoftwareConsortium/ITK
  git_rev: 786a1d59852ff40df453788c744a87b5c7027ddb

build:
    number: 0
    skip: True   # [win and py<36]
    features:
    - vc14  # [win and py>=36]

# Note: the run dependency on gxx_{} below is due to the fact that HDF5 includes GCC
#       wrapper compilers, so it needs the same stack. Otherwise we end up pulling
#       that stack from the host, and eventually get this error due to how ITK
#       creates the config, vs how conda does replacement for the placeholder text.
#       https://github.com/conda-forge/libitk-feedstock/issues/7

requirements:
  build:
    - {{ compiler("cxx") }}
    - cmake    >=3.3
    - ninja
    - python   # [win]
  host:
    - expat
    - hdf5     {{ hdf5_version }} # [unix]
    - jpeg
    - libtiff
    - libpng
    - zlib
    - vc 14    # [win and py>=36]
  run:
    - expat
    - hdf5     {{ hdf5_version }} # [unix]
    - jpeg
    - libtiff
    - libpng
    - zlib
    - vc 14  # [win and py>=36]

test:
  requires:
    - cmake
    - {{ compiler("cxx") }}
  files:
    - example
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
