{% set version = "5.0b01" %}

# NOTE: this could go back to 1.8 when bumping to >=v5.0b02, because compat was restored in
#       https://github.com/InsightSoftwareConsortium/ITK/commit/c090e650ab0e2062
{% set hdf5_version = ">=1.10.2" %}

package:
  name: libitk
  version: "{{version}}"

source:
  url: https://github.com/InsightSoftwareConsortium/ITK/archive/v{{version}}.tar.gz
  sha256: 0b744b4e367475426e57692c4509f99e74d2ef007579533767de6c7613b42b3c

build:
    number: 0
    skip: True   # [win and py<36]
    features:
    - vc14  # [win and py>=36]

requirements:
  build:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake    >=3.3
    - ninja
    - python   # [win]
  host:
    - expat    2.1.*
    - hdf5     {{ hdf5_version }} # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - vc 14    # [win and py>=36]
  run:
    - expat    2.1.*
    - hdf5     {{ hdf5_version }} # [not win]
    - jpeg     9*
    - libtiff  4.0.*
    - libpng   >=1.6.27,<1.7
    - zlib     1.2.*
    - vc 14  # [win and py>=36]

test:
  requires:
    - cmake
  files:
    - example
  commands:
    - test -d $PREFIX/include/ITK*                        # [not win]
    - if not exist %LIBRARY_INC%\\ITK* exit 1             # [win]
    - itkTestDriver -- echo "Runtime ITK OK"
    - cmake -D "CMAKE_SYSTEM_PREFIX_PATH:FILEPATH=${PREFIX}" ./example  # [not win]
    - cmake --build . --config Release                                  # [not win]

about:
  home: http://www.itk.org
  license: Apache 2.0
  license_file: LICENSE
  summary: Runtime libraries and header files for the Insight Toolkit for segmentation and registration.

extra:
    recipe-maintainers:
      - blowekamp
      - bluescarni
